name: Welcome Wagon 🚃

on: [pull_request_target, issues]

jobs:
  greet_newcomer:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          ## 👋 Hey there, Issue Explorer!

          Thanks for taking the time to report an issue. You're awesome for helping make this project better! 🌟

          A few quick things:
          - 📝 Please make sure you've included all relevant details
          - 🔍 Check if this issue has been reported before
          - 💡 If you have any ideas for solving this, we'd love to hear them!

          Happy coding, and thanks again for your contribution! 🚀
        pr-message: |
          ## 🎉 Woohoo! Your First Pull Request!

          Welcome aboard the collaboration train! 🚂 We're thrilled to see your contribution.

          Here's what happens next:
          1. 👀 Our team will review your changes
          2. 💬 We might suggest some tweaks or ask questions
          3. 🎯 Once everything looks good, we'll merge your PR

          Remember:
          - 🧪 Make sure all tests are passing
          - 📄 Update documentation if needed
          - 🙌 Be open to feedback and discussion

          You're now officially part of our developer community. Let's build amazing things together! 🌈🛠️
